-- Privacy-minimized recent activity tracking for platform operations.
-- Stores only activity category, feature name, user, household, and timestamp.

create table if not exists public.app_activity_logs (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  household_id uuid references public.households(id) on delete set null,
  activity_type text not null check (activity_type in ('session_open', 'session_resume', 'view_open', 'record_saved')),
  feature_name text not null check (char_length(feature_name) between 1 and 40),
  occurred_at timestamptz not null default now()
);

create index if not exists app_activity_logs_occurred_idx
  on public.app_activity_logs(occurred_at desc);
create index if not exists app_activity_logs_user_occurred_idx
  on public.app_activity_logs(user_id, occurred_at desc);
create index if not exists app_activity_logs_household_occurred_idx
  on public.app_activity_logs(household_id, occurred_at desc);

alter table public.app_activity_logs enable row level security;
revoke all on table public.app_activity_logs from anon, authenticated;

create or replace function public.log_app_activity(
  p_activity_type text,
  p_feature_name text,
  p_household_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_feature text := left(btrim(coalesce(p_feature_name, '')), 40);
begin
  if current_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if p_activity_type not in ('session_open', 'session_resume', 'view_open', 'record_saved') then
    raise exception 'invalid activity type' using errcode = '22023';
  end if;

  if normalized_feature = '' then
    raise exception 'feature name required' using errcode = '22023';
  end if;

  if p_household_id is not null and not public.is_household_member(p_household_id) then
    raise exception 'household membership required' using errcode = '42501';
  end if;

  -- Keep the table bounded without requiring a separate cron job.
  delete from public.app_activity_logs
  where occurred_at < now() - interval '90 days';

  -- Ignore rapid duplicate events generated by repeated taps or page hydration.
  if exists (
    select 1
    from public.app_activity_logs log
    where log.user_id = current_user_id
      and log.activity_type = p_activity_type
      and log.feature_name = normalized_feature
      and log.occurred_at >= now() - interval '20 seconds'
  ) then
    return;
  end if;

  insert into public.app_activity_logs(user_id, household_id, activity_type, feature_name)
  values (current_user_id, p_household_id, p_activity_type, normalized_feature);
end;
$$;

revoke all on function public.log_app_activity(text, text, uuid) from public;
grant execute on function public.log_app_activity(text, text, uuid) to authenticated;

create or replace function public.list_platform_recent_activity(
  p_since_at timestamptz default now() - interval '7 days',
  p_row_limit integer default 200
)
returns table (
  id bigint,
  user_id uuid,
  user_email text,
  user_name text,
  household_id uuid,
  household_name text,
  activity_type text,
  feature_name text,
  occurred_at timestamptz
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'platform administrator access required' using errcode = '42501';
  end if;

  return query
  select
    log.id,
    log.user_id,
    users.email::text,
    nullif(trim(coalesce(
      users.raw_user_meta_data ->> 'full_name',
      users.raw_user_meta_data ->> 'name',
      users.raw_user_meta_data ->> 'user_name',
      ''
    )), '')::text,
    log.household_id,
    households.name::text,
    log.activity_type,
    log.feature_name,
    log.occurred_at
  from public.app_activity_logs log
  join auth.users users on users.id = log.user_id
  left join public.households households on households.id = log.household_id
  where log.occurred_at >= greatest(
    coalesce(p_since_at, now() - interval '7 days'),
    now() - interval '90 days'
  )
  order by log.occurred_at desc
  limit least(greatest(coalesce(p_row_limit, 200), 1), 500);
end;
$$;

revoke all on function public.list_platform_recent_activity(timestamptz, integer) from public;
grant execute on function public.list_platform_recent_activity(timestamptz, integer) to authenticated;

comment on table public.app_activity_logs is
  'Privacy-minimized app activity. No titles, notes, measurements, photos, or content are stored.';
